# Generated by Django 5.2.8 on 2025-11-29 14:05

import library_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=225, verbose_name=library_app.models.Author),
        ),
    ]
